# Generated by Django 6.0.4 on 2026-04-17 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pots.pot')),
            ],
            options={
                'unique_together': {('pot', 'telegram_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drops_paid', to='pots.member')),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='pots.pot')),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='pots.drop')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='pots.member')),
            ],
        ),
    ]
