# Generated by Django 6.0.4 on 2026-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pot',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
