# Generated by Django 6.0.4 on 2026-04-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0002_member_telegram_username_pot_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
