# Generated by Django 6.0.4 on 2026-04-19 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0003_drop_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
