# Generated by Django 6.0.4 on 2026-04-19 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0005_compotuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='compotuser',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlaceholderClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='pots.member')),
            ],
        ),
    ]
