# Generated by Django 6.0.4 on 2026-04-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0007_shoppinglist_listmember_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItemSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='pots.shoppinglist')),
            ],
            options={
                'unique_together': {('shopping_list', 'name')},
            },
        ),
    ]
