# Generated by Django 6.0.4 on 2026-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0008_listitemsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compotuser',
            name='is_maintainer',
            field=models.BooleanField(default=False),
        ),
    ]
