# Generated by Django 6.0.4 on 2026-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0009_compotuser_is_maintainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='is_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
